<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="row custom-copyright">
    <div class="column-3">
        &nbsp;
    </div>
    <div class="column-3 text-center">
        <span class="demand-font">
           <a class="link-style" href="#"> PRIVACY POLICY</a> &nbsp; &nbsp; &nbsp; 
           <a class="link-style" href="#"> TERMS AND CONDITIONS</a> &nbsp; &nbsp; &nbsp; 
           <a class="link-style" href="#"> SITE MAP </a>
        </span>
    </div>

    <div class="column-3">
        <span class="demand-font">
           <a class="link-style" href="#"> &copy; RUDSAK 2019. ALL RIGHTS RESERVED.</a>
        </span>
    </div>
</div>
    