<div class="footer-bar">
	<img class="footer-arrow" src="<?php echo $this->getViewFileUrl('images/arrow.png'); ?>" /><span class="demanded-font footer-bar-text" >En ligne c’est bien, en boutique c’est mieux ! Venez vivre l’expertise Panda</span>
</div>

<div class="left-main-div max-width">
	<div class="left-div-1">
		<div class="fiull-width-inside-75">
			<div class="div-75-col-1">
				<u id="link-head">Panda</u><br>
				<ul>
					<li>
						<a href="#">À propos</a><br/>
					</li>
					<li>
						<a href="#">Cartes Cadeaux</a><br/>
					</li>
					<li>
						<a href="#">Le Club des Petits Pieds</a><br/>
					</li>
					<li>
						<a href="#">Nos conseils</a><br/>
					</li>
					<li>
						<a href="#">Politique de confidentialité</a><br/>
					</li>
					<li>
						<a href="#">Carrières</a><br/>
					</li>
					<li>
						<a href="#">Concours</a><br/>
					</li>
					<li>
						<a href="#">Pédimètre</a><br/>
					</li>
				</ul>

			</div>
		<div class="div-75-col-2" >
				<u id="link-head">Service à la clientèle</u><br/>
				<ul>
					<li> 
						<a href="#">Garantie de satisfaction</a><br/>
					</li>
					<li>
						<a href="#">Livraison</a><br/>
					</li>
					<li>
						<a href="#">Retours et échanges</a><br/>
					</li>
					<li>
						<a href="#">Contactez-nous</a><br/>
					</li>
					<li>
						<a href="#">Trouver un magasin</a><br/>
					</li>
				</ul>

				
				
				
				
			</div>
			<div class="div-75-col-3">
				<u id="link-head">Suivez-Nous </u><br/>
				<ul>
					<li>
						<a href="#"><i class="fa fa-facebook-f" style="font-size:12px !important"> </i> Facebook </a>	<br/>	
					</li>

					<li>
						<a href="#"><i class="fa fa-instagram " style="font-size:12px !important"> </i> Instagram </a>	<br/>	
					</li>

				</ul>
				
			</div>
		</div>
	</div>

	<div class="footer-25-img">
		<img src="<?php echo $this->getViewFileUrl('images/footer-girl.png'); ?>" />
		<img class="panda-footer-logo" src="<?php echo $this->getViewFileUrl('images/logo.png'); ?>" />
    <span class="panda-footer-text">Tous droits réservés</span>
	</div>
</div>