<div style="width:100%;">
	<div class="col-left">
		<div style="background-color: #C2C2D1; height:334px; ">
			<img src="<?php echo $this->getViewFileUrl('images/ecco.png'); ?>" class="ecco"/><br/>
			<img src="<?php echo $this->getViewFileUrl('images/shoes.png'); ?>" class="shoes" /><br/>
			<button class="col-left-btn" >Jetez un coup d'oeil</button>
		</div>

		<div style="background-color: #ECBEFA;  margin-top: 44px;">
			<img style="padding: 26px 0 0 24px;" src="<?php echo $this->getViewFileUrl('images/col-left-div-2.png'); ?>" /><br/>
			<img style="    margin-top: -55px;
    margin-bottom: -5px;
    padding: 0px 0 0 42px;" src="<?php echo $this->getViewFileUrl('images/left-div-girl.png'); ?>" />
		</div>

	</div>




	<div class="main-col"> 
		<div  class="demanded-font main-col-txt"> En vedettes</div>
	    <div style="padding:20px;">
	    	<img style="height: 586px;" src="<?php echo $this->getViewFileUrl('images/col-main-background.png'); ?>" />
	    </div>
	</div>



	
	<div class="col-right">
		<div style="background-color: #C9FBA9; height:334px;">
			<img src="<?php echo $this->getViewFileUrl('images/ecco.png'); ?>" class="ecco"/><br/>
			<img src="<?php echo $this->getViewFileUrl('images/shoe.png'); ?>" class="shoes" /><br/>
			<button class="col-left-btn">Jetez un coup d'oeil</button>	
		</div>

		<div>
			<div style="background-color: #B4EDE3;  margin-top: 44px;">
			<img style="padding: 26px 0 0 24px;" src="<?php echo $this->getViewFileUrl('images/col-right-div-2.png'); ?>" /><br/>
			<img style="    margin-top: -86px;
    margin-bottom: -5px;
    padding: 0px 0 0 42px;" src="<?php echo $this->getViewFileUrl('images/right-div-boy.png'); ?>" />
		</div>	
		</div>
		
	</div>

</div>





<div>
	<span>Nos Produits</span>	
</div>