<?php
    // //$test = $block->grabbingProductList();
    // $helper = $this->helper('Excellence\SliderModule\Helper\Data');
    // $productCollection = $helper->getProductCollection();
    // // echo get_class($block);
    // //echo "<pre>";
    // // die('testt');
    // foreach ($productCollection as $product){
    //     echo $product->getName().'<br>';
    //     echo $product->getSKU().'<br/>';
    //     echo $product->getImage().'<br/>';
        
    // }
    // die;
?>


<!--
<div class="row">
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>leaf.png"  alt="100%-canadian-design"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>100.png"  alt="100%-canadian-design"/>
    </div>
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>shield.png"  alt="shield"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>established.png"  alt="established"/>
    </div>
    <div class="column-3">
        <img src="<?php echo $block->getUrl("pub/media/images")?>snap.png"  alt="snap"/><br/>
        <img src="<?php echo $block->getUrl("pub/media/images")?>genuine.png"  alt="genuine"/>
    </div>
</div>
-->

<!--
<div>
    <div class="column-2 back-img">
            <img class="full-width" src="<?php echo $block->getUrl("pub/media/images")?>shot1.png"  alt="100%-canadian-design"/><br/>
            <div class="centered">
                <img src="<?php echo $block->getUrl("pub/media/images")?>up-to-30.png"  alt="up-to-30"/><br/>
            </div>
    </div>

    <div class="column-2 back-img">
        <img class="full-width" src="<?php echo $block->getUrl("pub/media/images")?>handbags.png"  alt="hand-bags"/><br/>
        <div class="centered">
            <img src="<?php echo $block->getUrl("pub/media/images")?>because.png"  alt="up-to-30"/><br/>
            <img src="<?php echo $block->getUrl("pub/media/images")?>celebrate.png"  alt="up-to-30"/><br/>
        </div>
    </div>

</div>
-->

<!-- above link set pending -->
<!--
<div>
    <div class="column-2" style="text-align:left; margin-top:-1%;">
        <img src="<?php echo $this->getViewFileUrl("images/black-women.png"); ?>"  alt="up-to-30"/>
    </div>

    <div class="column-2 women-catalog-slider">
        <div class="catalog-text">
            <img src="<?php echo $this->getViewFileUrl("images/femmes.png"); ?>" alit="slide1"  /><br/>
            <img style="padding-top: 4%;" src="<?php echo $this->getViewFileUrl("images/lora-ipsum.png"); ?>" alit="slide1"  />
        </div>

        <?php
            
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('women-catalog-slider')
            ->toHtml();
        ?>
    </div>
</div>
-->




<!--
<div style="width:100%; float:left;" >
    

    <div class="column-2 men-catalog-slider">
        <div class="catalog-text">
            <img src="<?php echo $this->getViewFileUrl("images/hommes.png"); ?>" alit="slide1"  /><br/>
            <img style="padding-top: 4%;" src="<?php echo $this->getViewFileUrl("images/lora-ipsum.png"); ?>" alit="slide1"  />
        </div>

        <?php
            
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('men-catalog-slider')
            ->toHtml();
        ?>
    </div>

    <div class="column-2" style="margin-top: -0.8%;">
        <img src="<?php echo $this->getViewFileUrl("images/men-black-white.png"); ?>"  alt="up-to-30"/>
    </div>
</div>
-->







<script>
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        // 'use strict';
        // $.noConflict();

        //less-essential-slider
        $(".less-essential-slider").owlCarousel({
            loop:true,
            margin:10,
            nav:false,
            items: 5,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:5
                }
            }
        });


        //men-catalog-carousel
        $(".men-slider").owlCarousel({
            loop:true,
            margin:10,
            nav:false,
            items: 2,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:2
                }
            }
        });

        //women-catalog-slider

        $(".women-slider").owlCarousel({
            loop:true,
            margin:10,
            nav:false,
            items: 2,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:2
                }
            }
        });


        
    });
</script>
